version: "3.8"
x-common:
  database:
    &db-environment
#    Change these! These are sensitive secrets.
    MYSQL_USER: &db-user "freebooter"  # Only change the username
    MYSQL_PASSWORD: &db-password "password"  # Only change the password
    MYSQL_ROOT_PASSWORD: "root-password"  # Only change the password
  proxy:
    TOR_PROXY_PASSWORD: &tor-password "test1234"  # Only change the password
services:
  mariadb:
    image: mariadb:10
    hostname: mariadb
    restart: always
    ports:
      - "3306:3306/tcp"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "freebooter"
    volumes:
      - mariadb:/var/lib/mysql
  torproxy:
    image: "dperson/torproxy"
    hostname: torproxy
    restart: always
    ports:
      - "9050:9050/udp"
      - "9051:9051/tcp"
    environment:
      PASSWORD: *tor-password
  adminer:
    image: "adminer:4-standalone"
    restart: always
    ports:
      - "8080:8080/tcp"
    depends_on:
      - mariadb
  freebooter:
    image: ghcr.io/nefarium/freebooter:latest
    build: .
    restart: unless-stopped
    environment:
      # MariaDB connection
      FREEBOOTER_MYSQL_HOST: mariadb
      FREEBOOTER_MYSQL_PORT: 3306
      FREEBOOTER_MYSQL_DATABASE: "freebooter"
      FREEBOOTER_MYSQL_USER: *db-user
      FREEBOOTER_MYSQL_PASSWORD: *db-password
      # Tor proxy connection
      FREEBOOTER_TOR_PROXY_HOST: torproxy
      FREEBOOTER_TOR_PROXY_PORT: 9050
      FREEBOOTER_TOR_PROXY_CONTROL_PORT: 9051
      FREEBOOTER_TOR_PROXY_PASSWORD: *tor-password
      # Freebooter configuration
      # FREEBOOTER_DISCORD_WEBHOOK: "https://discord.com/api/webhooks/12345/abcde"
      # FREEBOOTER_DISCORD_WEBHOOK_MESSAGE: "<@12345>"
    volumes:
      - config:/app/config
      - scratch:/app/scratch
      # - input:/app/input
      # - output:/app/output
    depends_on:
      - mariadb
      - torproxy
volumes:
  mariadb:
  config:
  scratch:
  # input:
  # output:
